services:
  db:
    container_name: postgres-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: api_games
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis-cache
    image: redis:7.4.1-alpine
    # restart: unless-stopped
    ports:
      - '6378:6378'
  app:
    container_name: games-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5002:5002'
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASS=admin
      - DB_NAME=api_games
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RAWG_API_KEY=ce96e569f10a48279757040a97b56201
      - PORT=5002
    depends_on:
      - db
      - redis

volumes:
  postgres-data:
  redis: